communication_task:
  description: >
    사용자로부터 받은 메시지('{message}')를 단계별로 분석합니다.
    1. 질문의 핵심 키워드와 숨은 의도를 파악합니다.
    2. 필요 시, 웹 검색 도구를 사용하여 관련 최신 정보를 찾습니다.
    3. 수집된 정보를 종합하여 사용자가 이해하기 쉬운 형태로 명확하고 친절한 답변을 생성합니다.

  expected_output: >
    사용자의 질문 의도에 완벽하게 부합하는, 명확하고 간결하며 친절한 톤의 한국어 답변.
    질문정보성 질문의 경우, 핵심 내용을 요약하고 신뢰할 수 있는 출처(URL)를 포함해야 합니다.
  agent: communication_agent
