default_agent: agent_core
agents:
  agent_core:
    name: agent_core
    entrypoint: agent_core.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::129231402580:role/bedrock-role
      execution_role_auto_create: true
      account: '129231402580'
      region: us-east-1
      ecr_repository: 129231402580.dkr.ecr.us-east-1.amazonaws.com/agents
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: agent_core-wdKDoxDJ7Y
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:129231402580:runtime/agent_core-wdKDoxDJ7Y
      agent_session_id: 08935d43-86fa-412a-a31a-5a0d09e9c48a
    codebuild:
      project_name: bedrock-agentcore-agent_core-builder
      execution_role: arn:aws:iam::129231402580:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-6c14ccb6af
      source_bucket: bedrock-agentcore-codebuild-sources-129231402580-us-east-1
    authorizer_configuration: null
    oauth_configuration: null
